### ISSUE TITLE
Class constructor must not have parameters

### ISSUE THREAD

**Issue by thomas-klambauer** [ben-gibson/GitLink#132]
**Describe the bug**
Error in logfile

**To Reproduce**
Start up IntelliJ with my project

**Expected behavior**
No error

**Screenshots**
Nothing UI visible

**Desktop (please complete the following information):**
OS: debian

`
2021-03-12 13:23:59,423 [7464866]  ERROR - tellij.openapi.util.ObjectTree - IntelliJ IDEA 2020.3.2  Build #IU-203.7148.57 
2021-03-12 13:23:59,423 [7464866]  ERROR - tellij.openapi.util.ObjectTree - JDK: 11.0.9.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-03-12 13:23:59,423 [7464866]  ERROR - tellij.openapi.util.ObjectTree - OS: Linux 
2021-03-12 13:23:59,424 [7464867]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2021-03-12 13:23:59,425 [7464868]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
2021-03-12 13:24:01,156 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2021-03-12 13:24:01,246 [     90]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IU-203.7148.57, 26 Jan 2021 03:24) 
2021-03-12 13:24:01,276 [    120]   INFO -        #com.intellij.idea.Main - OS: Linux (4.19.0-14-amd64, amd64) 
2021-03-12 13:24:01,295 [    139]   INFO -        #com.intellij.idea.Main - JRE: 11.0.9.1+11-b1145.77 (JetBrains s.r.o.) 
2021-03-12 13:24:01,296 [    140]   INFO -        #com.intellij.idea.Main - JVM: 11.0.9.1+11-b1145.77 (OpenJDK 64-Bit Server VM) 
2021-03-12 13:24:01,296 [    140]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx10000m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -XX:CICompilerCount=2 -Djdk.http.auth.tunneling.disabledSchemes="" -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Djdk.attach.allowAttachSelf=true -Dkotlinx.coroutines.debug=off -Djdk.module.illegalAccess.silent=true -Dsun.tools.attach.tmp.only=true -Dide.no.platform.update=true -Dsun.io.useCanonCaches=false -XX:ReservedCodeCacheSize=512m -Didea.plugins.path=/home/thomas/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57.plugins -XX:ErrorFile=/home/thomas/java_error_in_idea_%p.log -XX:HeapDumpPath=/home/thomas/java_error_in_idea_.hprof -Didea.vendor.name=JetBrains -Didea.paths.selector=IntelliJIdea2020.3 -Djb.vmOptionsFile=/home/thomas/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57.vmoptions -Didea.jre.check=true 
2021-03-12 13:24:01,297 [    141]   INFO -        #com.intellij.idea.Main - library path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib 
2021-03-12 13:24:01,297 [    141]   INFO -        #com.intellij.idea.Main - boot library path: /home/thomas/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57/jbr/lib 
2021-03-12 13:24:01,377 [    221]   INFO -        #com.intellij.idea.Main - locale=es_ES JNU=UTF-8 file.encoding=UTF-8
  idea.config.path=/home/thomas/.config/JetBrains/IntelliJIdea2020.3
  idea.system.path=/home/thomas/.cache/JetBrains/IntelliJIdea2020.3
  idea.plugins.path=/home/thomas/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57.plugins
  idea.log.path=/home/thomas/.cache/JetBrains/IntelliJIdea2020.3/log 
2021-03-12 13:24:01,459 [    303]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 81 ms 
2021-03-12 13:24:03,031 [   1875]   INFO - ntellij.idea.ApplicationLoader - CPU cores: 8; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@2a489083[Running, parallelism = 7, size = 1, active = 0, running = 0, steals = 7, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@5b66f237 
2021-03-12 13:24:03,060 [   1904]   INFO - ntellij.idea.ApplicationLoader - WM detected: GNOME Shell 

...

2021-03-12 13:25:31,313 [  90157]   INFO - egistry.NpmRegistryServiceImpl - Found 25 dist-tags, 157 versions for @types/lodash in 128ms 
2021-03-12 13:25:31,366 [  90210]   INFO - egistry.NpmRegistryServiceImpl - Found 25 dist-tags, 148 versions for @types/jest in 51ms 
2021-03-12 13:25:37,949 [  96793]   INFO - j.compiler.server.BuildManager - Using preloaded build process to compile /mnt/data/workspaces/cluster/building 
2021-03-12 13:25:38,487 [  97331]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /home/thomas/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57/plugins/java/lib/jps-launcher.jar:/mnt/data/devtools/openjdk1.8.0_265_x64/lib/tools.jar 
2021-03-12 13:25:44,029 [ 102873]   INFO - rationStore.ComponentStoreImpl - Saving appGithubAccounts took 39 ms 
2021-03-12 13:25:44,335 [ 103179]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=dynatrace-saas, containerState=COMPONENT_CREATED, componentStore=/mnt/data/workspaces/cluster/building)RunManager took 114 ms 
2021-03-12 13:25:44,658 [ 103502]   WARN - Container.ComponentManagerImpl - Class constructor must not have parameters: uk.co.ben_gibson.git.link.UI.Settings.ConfigurableSettings [Plugin: uk.co.ben-gibson.remote.repository.mapper] 
com.intellij.diagnostic.PluginException: Class constructor must not have parameters: uk.co.ben_gibson.git.link.UI.Settings.ConfigurableSettings [Plugin: uk.co.ben-gibson.remote.repository.mapper]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:765)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:425)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:332)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:45)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:94)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getId(ConfigurableWrapper.java:214)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.groupConfigurables(ConfigurableExtensionPointUtil.java:264)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:126)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.lambda$getConfigurableGroup$1(ConfigurableExtensionPointUtil.java:116)
	at com.intellij.openapi.util.ClearableLazyValue$2.compute(ClearableLazyValue.java:26)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:9)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:113)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:114)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:53)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:55)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:615)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:522)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:892)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-03-12 13:25:44,671 [ 103515]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=uk.co.ben_gibson.git.link.UI.Settings.ConfigurableSettings) 
2021-03-12 13:25:45,009 [ 103853]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting 
2021-03-12 13:25:45,312 [ 104156]   INFO - eStyle.CommonCodeStyleSettings - Loaded Java common code style settings 
2021-03-12 13:25:46,281 [ 105125]   INFO -  #git4idea.commands.GitHandler - git log took 15221 ms. Command parameters: 
setsid /usr/bin/git -c core.quotepath=false -c log.showSignature=false log --pretty=format:%x01%x01%H%x02%x02%P%x02%x02%ct%x02%x02%an%x02%x02%ae%x02%x02%d%x03%x03 --encoding=UTF-8 --decorate=full HEAD --branches --remotes --tags --date-order -- 
2021-03-12 13:26:00,385 [ 119229]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=dynatrace-saas, containerState=COMPONENT_CREATED, componentStore=/mnt/data/workspaces/cluster/building)RunManager took 56 ms 
2021-03-12 13:26:04,627 [ 123471]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=dynatrace-saas, containerState=COMPONENT_CREATED, componentStore=/mnt/data/workspaces/cluster/building)RunManager took 56 ms 
`

**Comment by ben-gibson** [comment]
👀

**Comment by ben-gibson** [comment]
This should be fixed in the latest version 3.3.4, can you confirm?

**Comment by thomas-klambauer** [comment]
Thanks Ben! I updated the plugin and don't see anything in the logfile.
However I wasn't able to reproduce it on demand to fully confirm it.
Feel free to close when done from your side.
