### ISSUE TITLE
Exception if invoking "Open in GitHub" at the project top level

### ISSUE THREAD

**Issue by ecerulm** [ben-gibson/GitLink#141]
**Describe the bug**

I get 

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -28, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at uk.co.ben_gibson.git.link.Git.File.directoryPath(File.java:23)
	at uk.co.ben_gibson.git.link.Url.Substitution.URLTemplateProcessor.processFile(URLTemplateProcessor.java:78)
	at uk.co.ben_gibson.git.link.Url.Substitution.URLTemplateProcessor.process(URLTemplateProcessor.java:63)
	at uk.co.ben_gibson.git.link.Url.Substitution.URLTemplateProcessor.process(URLTemplateProcessor.java:36)
	at uk.co.ben_gibson.git.link.Url.Factory.TemplatedUrlFactory.createUrlToFileAtCommit(TemplatedUrlFactory.java:80)
	at uk.co.ben_gibson.git.link.GitLink$1.run(GitLink.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. Select project on Project explorer
2. Right click and choose "Open in GitHub" 
3. You will get a IntelliJ notification that there was an exception in the event log (the first time only)

**Expected behavior**

I would expect that it produces a link to the GitHub project overview page (well in my case it's a gitlab.com project) 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ecerulm** [comment]
@ben-gibson , it is closed because it's fixed now?

**Comment by ben-gibson** [comment]
This should be fixed in version 4 🤞
