### ISSUE TITLE
Exception String out of bounds opening gitlab link to git submodule link

### ISSUE THREAD

**Issue by tobidelbruck** [ben-gibson/GitLink#149]
**Describe the bug**
Got this exception below when trying to browse to a git submodule https://gitlab.lrz.de/tum-cps/commonroad-vehicle-models.git

````
java.lang.StringIndexOutOfBoundsException: begin 0, end -25, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at uk.co.ben_gibson.git.link.Git.File.directoryPath(File.java:23)
	at uk.co.ben_gibson.git.link.Url.Substitution.URLTemplateProcessor.processFile(URLTemplateProcessor.java:78)
	at uk.co.ben_gibson.git.link.Url.Substitution.URLTemplateProcessor.process(URLTemplateProcessor.java:63)
	at uk.co.ben_gibson.git.link.Url.Substitution.URLTemplateProcessor.process(URLTemplateProcessor.java:46)
	at uk.co.ben_gibson.git.link.Url.Factory.TemplatedUrlFactory.createUrlToFileOnBranch(TemplatedUrlFactory.java:66)
	at uk.co.ben_gibson.git.link.GitLink$1.run(GitLink.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
````

**To Reproduce**
1. Have this git submodule in a project
1. Select the submodule folder from Project pane
2. Right click, select Open in github
4. See exception above

**Expected behavior**
Open the gitlab page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Comment by tobidelbruck** [comment]
The .gitmodules file in our project l2race https://github.com/neuromorphs/l2race contains

````
[submodule "commonroad-vehicle-models"]
	path = commonroad-vehicle-models
	url = https://gitlab.lrz.de/tum-cps/commonroad-vehicle-models.git
````
