### ISSUE TITLE
context menu broken and spinner showing: Cannot create class

### ISSUE THREAD

**Issue by axaluss** [ben-gibson/GitLink#151]
**Describe the bug**
Can't remember well what I was doing. 
I think I was using the "find action" dialog.
 I just got the error popup.
Now noticed that the rightclick context menu is broken and just shows a spinner when opened on a method like here https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000318564-Permanent-spinner.
  

info
```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021 
Subscription is active until February 19, 2022.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: claims.bold.intellij.avro (0.3.1), com.intellij.ideolog (203.0.27.0), com.tabnine.TabNine (0.4.6), de.netnexus.camelcaseplugin (3.0.8), net.seesharpsoft.intellij.plugins.csv (2.17.1), org.antlr.intellij.plugin (1.16), git-commit-message-plugin (1.3), uk.co.ben-gibson.remote.repository.mapper (3.3.3), org.plugin.dot.id (1.2), org.toml.lang (0.2.152.4026-212), Error-prone plugin (212.4746.52), zielu.gittoolbox (212.6.6), GrepConsole (11.10.211.6086.0), org.jetbrains.plugins.hocon (2021.1.0), Pythonid (212.4746.96), org.intellij.scala (2021.2.15), zio.intellij.zio-intellij (2021.2.11.1), izhangzhihao.rainbow.brackets (6.19), org.rust.lang (0.4.152.4026-212)
Kotlin: 212-1.5.10-release-IJ4746.92
```

trace
```
Cannot create configurable

com.intellij.diagnostic.PluginException: Cannot create class uk.co.ben_gibson.git.link.UI.Settings.ConfigurableSettings (classloader=PluginClassLoader(plugin=PluginDescriptor(name=GitLink, id=uk.co.ben-gibson.remote.repository.mapper, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/GitLink, version=3.3.3, package=null), packagePrefix=null, instanceId=43, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:870)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:887)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:440)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:346)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:42)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:116)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:91)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getId(ConfigurableWrapper.java:211)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:83)
	at com.intellij.openapi.util.NotNullLazyValue$3.compute(NotNullLazyValue.java:99)
	at com.intellij.openapi.util.NotNullLazyValue$3.getValue(NotNullLazyValue.java:84)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:368)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:151)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:97)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:99)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(Project,UrlModifierProvider)ConfigurableSettings to ()Object
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:861)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:847)
	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:495)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:854)
	... 27 more
```

**Comment by axaluss** [comment]
might need more changes in https://github.com/ben-gibson/GitLink/pull/150

**Comment by axaluss** [comment]
duplicate of https://github.com/ben-gibson/GitLink/issues/143

**Comment by axaluss** [comment]
it's fixed in latest version
