### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by G-Rath** [ben-gibson/GitLink#43]
Error message: null.

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:903)
	at java.util.ArrayList$Itr.next(ArrayList.java:853)
	at uk.co.ben_gibson.open.in.git.host.Configuration.<init>(Configuration.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:341)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:267)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.a(ConfigurableWrapper.java:58)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:117)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:98)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:138)
	at com.intellij.openapi.options.ex.Weighted.a(Weighted.java:35)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:175)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:53)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:86)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:89)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:80)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.g(SearchEverywhereAction.java:1966)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1374)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm working in a standard GIT project in IntelliJ, and was changing files with shift+shift when this error occurred.

**Comment by ben-gibson** [comment]
Are you still able to consistently reproduce this?

**Comment by G-Rath** [comment]
I've never been able to consistently reproduce it - It just happened one day when I was coding. I'll keep an eye out for it, and trying doing a couple of quick tests right now, but I suspect it's a bit of a heisenbug that occurs when a couple of things align. 

Specifically I suspect it's caused by changing files quickly while the IDE is busy doing something else (like possibly a VCS refresh). 

I'll do a quick check of my logs as well, see if that has more information.

**Comment by G-Rath** [comment]
This is all my logs have on the matter - Theres no events before or after these for a good number of minutes (i.e nothing help like 'refreshing git indexes' just before the exception).

```
2017-10-10 11:48:56,587 [5654222]  ERROR - openapi.options.ConfigurableEP - null 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:903)
	at java.util.ArrayList$Itr.next(ArrayList.java:853)
	at uk.co.ben_gibson.open.in.git.host.Configuration.<init>(Configuration.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:341)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:267)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.a(ConfigurableWrapper.java:58)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:117)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:98)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:138)
	at com.intellij.openapi.options.ex.Weighted.a(Weighted.java:35)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:175)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:53)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:86)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:89)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:80)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.g(SearchEverywhereAction.java:1966)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1374)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-10 11:48:56,588 [5654223]  ERROR - openapi.options.ConfigurableEP - IntelliJ IDEA 2017.2.5  Build #IU-172.4343.14 
2017-10-10 11:48:56,589 [5654224]  ERROR - openapi.options.ConfigurableEP - JDK: 1.8.0_152-release 
2017-10-10 11:48:56,589 [5654224]  ERROR - openapi.options.ConfigurableEP - VM: OpenJDK 64-Bit Server VM 
2017-10-10 11:48:56,589 [5654224]  ERROR - openapi.options.ConfigurableEP - Vendor: JetBrains s.r.o 
2017-10-10 11:48:56,589 [5654224]  ERROR - openapi.options.ConfigurableEP - OS: Windows 10 
2017-10-10 11:48:56,590 [5654225]  ERROR - openapi.options.ConfigurableEP - Assertion failed: Bundle missed for uk.co.ben_gibson.open.in.git.host.Configuration 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.openapi.options.ConfigurableEP.getDisplayName(ConfigurableEP.java:72)
	at com.intellij.openapi.options.ConfigurableEP.toString(ConfigurableEP.java:279)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:98)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:138)
	at com.intellij.openapi.options.ex.Weighted.a(Weighted.java:35)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:175)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:53)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:86)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:89)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:80)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.g(SearchEverywhereAction.java:1966)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1374)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-10 11:48:56,590 [5654225]  ERROR - openapi.options.ConfigurableEP - IntelliJ IDEA 2017.2.5  Build #IU-172.4343.14 
2017-10-10 11:48:56,590 [5654225]  ERROR - openapi.options.ConfigurableEP - JDK: 1.8.0_152-release 
2017-10-10 11:48:56,590 [5654225]  ERROR - openapi.options.ConfigurableEP - VM: OpenJDK 64-Bit Server VM 
2017-10-10 11:48:56,590 [5654225]  ERROR - openapi.options.ConfigurableEP - Vendor: JetBrains s.r.o 
2017-10-10 11:48:56,590 [5654225]  ERROR - openapi.options.ConfigurableEP - OS: Windows 10 
2017-10-10 11:48:56,590 [5654225]  ERROR - actions.SearchEverywhereAction - Argument for @NotNull parameter 'pathToBundle' of com/intellij/AbstractBundle.getResourceBundle must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'pathToBundle' of com/intellij/AbstractBundle.getResourceBundle must not be null
	at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java)
	at com.intellij.openapi.options.ConfigurableEP.getDisplayName(ConfigurableEP.java:73)
	at com.intellij.openapi.options.ConfigurableEP.toString(ConfigurableEP.java:279)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:98)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:138)
	at com.intellij.openapi.options.ex.Weighted.a(Weighted.java:35)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:175)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:53)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:86)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:89)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:80)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.g(SearchEverywhereAction.java:1966)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1374)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-10 11:48:56,591 [5654226]  ERROR - actions.SearchEverywhereAction - IntelliJ IDEA 2017.2.5  Build #IU-172.4343.14 
2017-10-10 11:48:56,591 [5654226]  ERROR - actions.SearchEverywhereAction - JDK: 1.8.0_152-release 
2017-10-10 11:48:56,591 [5654226]  ERROR - actions.SearchEverywhereAction - VM: OpenJDK 64-Bit Server VM 
2017-10-10 11:48:56,591 [5654226]  ERROR - actions.SearchEverywhereAction - Vendor: JetBrains s.r.o 
2017-10-10 11:48:56,591 [5654226]  ERROR - actions.SearchEverywhereAction - OS: Windows 10 
```

**Comment by ben-gibson** [comment]
Weird, thanks for the this though, I will keep any eye for it.
